# Generated by Django 5.1.1 on 2024-10-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "读书", "verbose_name_plural": "读书"},
        ),
    ]
